[general]
YOUTUBE_VIDEO_ID=""
ADMIN_EMAIL=""
ADMIN_NAME=""

[auth]
redirect_uri=""
cookie_secret=""

[auth.google]
client_id=""
client_secret=""
server_metadata_url=""

[api_key]
GEMINI_API_KEY=""
GOOGLE_API_KEY="
GROQ_API_KEY = ""
NASA_API_KEY=""
NEWS_API_KEY=""
OpenAI_API_KEY="sk-"
SPOONACULAR_API_KEY=""
TMDB_API_KEY=""
UBERDUCK_API_KEY=""
VISION_API_KEY=""
WEATHER_API_KEY=""
WOLFRAM_API_KEY=""
YOUTUBE_API_KEY=""

[spotify]
SPOTIFY_CLIENT_ID=""
SPOTIFY_CLIENT_SECRET=""

[kaggle]
KAGGLE_USERNAME=""
KAGGLE_KEY=""

[dogBreedClassificationModel]
MODEL="1O0vm50puB3FpWWpS53mB1_FazCRJXjvp"
